apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: myapp
      image: busybox
      command:
        [
          "/bin/sh",
          "-c",
          "while true; do cat /etc/config/app.env; sleep 5; done",
        ]
      volumeMounts:
        - name: config-volume
          mountPath: "/etc/config"
  volumes:
    - name: config-volume
      configMap:
        name: app-config
