name: Frontend CI/CD (React Vite)

on:
  workflow_dispatch: # 🚀 수동 실행 트리거
    inputs:
      action:
        type: choice
        description: "선택할 작업"
        required: true
        options:
          - Build Only
          - Build & Push
          - Deploy

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.inputs.action == 'Build Only' || github.event.inputs.action == 'Build & Push' || github.event.inputs.action == 'Deploy'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build React Image
        run: docker buildx build --platform linux/amd64 -t react-vite:latest -f react-frontend/Dockerfile .

  push:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.inputs.action == 'Build & Push' || github.event.inputs.action == 'Deploy'
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Push to Artifact Registry
        run: |
          docker tag react-vite:latest asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/react-repo/react-vite:latest
          docker push asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/react-repo/react-vite:latest

  deploy:
    runs-on: ubuntu-latest
    needs: push
    if: github.event.inputs.action == 'Deploy'
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy to GKE
        run: |
          gcloud container clusters get-credentials ${{secrets.GKE_CLUSTER_NAME}} --zone ${{ secrets.GKE_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}
          kubectl apply -f react-frontend/k8s/
          kubectl rollout status deployment/react-vite
  # build-and-push:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v2

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2

  #     - name: Authenticate to Google Cloud
  #       uses: google-github-actions/auth@v1
  #       with:
  #         credentials_json: ${{ secrets.GCP_CREDENTIALS }}

  #     - name: Configure Docker for GCP
  #       run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev

  #     - name: Build and Push React Image
  #       run: |
  #         docker buildx build --platform linux/amd64 -t asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/react-repo/react-vite:latest -f react-frontend/Dockerfile --push .
